name: Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Firefox
      run: |
        mkdir -p firefox
        cp -R -t firefox *.{js,css,html,json,png} LICENSE
    - uses: actions/upload-artifact@v2
      with:
        name: firefox
        path: firefox
